# Generated by Django 5.0.2 on 2024-04-21 10:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название мероприятия + грамота, сертификат и т.п', max_length=200, null=True, unique=True, verbose_name='Название шаблона')),
                ('path_to_file', models.CharField(help_text='Полный путь до хранящегося на локальном диске pdf файла', max_length=200, null=True, verbose_name='Путь до шаблона на локальном диске')),
                ('doc_type', models.CharField(choices=[('w', 'Шаблон с организацией'), ('wo', 'Шаблон без организации')], default='wo', help_text='Указывается ли организация в шаблоне или нет', max_length=2, verbose_name='Тип документа')),
                ('creation_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время создания шаблона', verbose_name='Дата и время создания шаблона')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'ordering': ['id', '-creation_datetime'],
                'indexes': [models.Index(fields=['name'], name='template_name'), models.Index(fields=['doc_type'], name='template_doc_type')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Полное имя участника мероприятия. Не длиннее 120 символов', max_length=120, verbose_name='ФИО')),
                ('organization_name', models.CharField(blank=True, help_text='Если в шаблоне есть поле организации, поле заполняется', max_length=200, null=True, verbose_name='Название организации участника')),
                ('creation_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время добавления участника мероприятия', verbose_name='Дата и время добавления участника мероприятия')),
                ('template', models.ForeignKey(help_text='Выбранный при заполнении шаблон документа', on_delete=django.db.models.deletion.CASCADE, to='constructor.template', verbose_name='Относится к документну')),
            ],
        ),
    ]
