# Generated by Django 5.0.2 on 2024-03-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_column='Мероприятие', help_text='Мероприятие, к которому относится шаблон', max_length=200, verbose_name='Мероприятие')),
            ],
        ),
    ]
