# Generated by Django 5.0.2 on 2024-05-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['id', '-creation_datetime'], 'verbose_name': 'Участник мероприятия', 'verbose_name_plural': 'Участникик мероприятия'},
        ),
        migrations.AddField(
            model_name='template',
            name='fullname_x_coordinate',
            field=models.IntegerField(default=0, help_text='Определяется автоматически при загрузке шаблона', verbose_name='Х координата текстового поля ФИО'),
        ),
        migrations.AddField(
            model_name='template',
            name='fullname_y_coordinate',
            field=models.IntegerField(default=0, help_text='Определяется автоматически при загрузке шаблона', verbose_name='Y координата текстового поля ФИО'),
        ),
        migrations.AddField(
            model_name='template',
            name='organization_x_coordinate',
            field=models.IntegerField(help_text='Определяется автоматически при загрузке шаблона', null=True, verbose_name='Х координата текстового поля названия организации'),
        ),
        migrations.AddField(
            model_name='template',
            name='organization_y_coordinate',
            field=models.IntegerField(help_text='Определяется автоматически при загрузке шаблона', null=True, verbose_name='Y координата текстового поля названия организации'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['fullname'], name='participant_fullname'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['template'], name='participant_template'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['organization_name'], name='participant_organization_name'),
        ),
    ]
