# Generated by Django 5.0.2 on 2024-05-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='fullname_textbox_height',
            field=models.IntegerField(default=0, help_text='Определяется автоматически при загрузке шаблона', verbose_name='Высота текстового поля ФИО'),
        ),
        migrations.AddField(
            model_name='template',
            name='fullname_textbox_width',
            field=models.IntegerField(default=0, help_text='Определяется автоматически при загрузке шаблона', verbose_name='Ширина текстового поля ФИО'),
        ),
        migrations.AddField(
            model_name='template',
            name='organization_textbox_height',
            field=models.IntegerField(help_text='Определяется автоматически при загрузке шаблона', null=True, verbose_name='Высота текстового поля названия организации'),
        ),
        migrations.AddField(
            model_name='template',
            name='organization_textbox_width',
            field=models.IntegerField(help_text='Определяется автоматически при загрузке шаблона', null=True, verbose_name='Ширина текстового поля названия организации'),
        ),
    ]
