# Generated by Django 5.0.2 on 2024-03-24 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_alter_template_options_remove_template_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата создания шаблона', verbose_name='Дата создания шаблона'),
        ),
        migrations.AlterField(
            model_name='template',
            name='doc_type',
            field=models.CharField(choices=[('w', 'Документ с организацией'), ('wo', 'Документ без организации')], default='wo', help_text='Указывается ли организация в шаблоне или нет', max_length=2, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text='Название мероприятия + грамота, сертификат и т.п', max_length=200, null=True, unique=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='template',
            name='path_to_file',
            field=models.CharField(help_text='Относительный путь до хранящегося pdf файла', max_length=200, null=True, verbose_name='Относительный путь до шаблона'),
        ),
    ]
