# Generated by Django 5.0.2 on 2024-03-24 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_alter_template_creation_date_alter_template_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создания шаблона', verbose_name='Дата создания шаблона'),
        ),
    ]
