# Generated by Django 5.0.2 on 2024-03-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_alter_template_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['pk', '-creation_date', 'name'], 'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
        migrations.AlterField(
            model_name='template',
            name='doc_type',
            field=models.CharField(choices=[('w', 'Шаблон с организацией'), ('wo', 'Шаблон без организации')], default='wo', help_text='Указывается ли организация в шаблоне или нет', max_length=2, verbose_name='Тип документа'),
        ),
    ]
