# Generated by Django 5.0.2 on 2024-03-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_alter_template_options_alter_template_doc_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['pk', '-creation_datetime', 'name'], 'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
        migrations.RenameField(
            model_name='template',
            old_name='creation_date',
            new_name='creation_datetime',
        ),
    ]
