# Generated by Django 5.0.2 on 2024-03-28 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_alter_template_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['id', '-creation_datetime', 'name'], 'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
        migrations.AlterField(
            model_name='template',
            name='creation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создания шаблона', verbose_name='Дата и время создания шаблона'),
        ),
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text='Название мероприятия + грамота, сертификат и т.п', max_length=200, null=True, unique=True, verbose_name='Название шаблона'),
        ),
        migrations.AlterField(
            model_name='template',
            name='path_to_file',
            field=models.CharField(help_text='Полный путь до хранящегося на локальном диске pdf файла', max_length=200, null=True, verbose_name='Путь до шаблона на локальном диске'),
        ),
    ]
