# Generated by Django 5.0.2 on 2024-03-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0007_alter_template_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['id', '-creation_datetime'], 'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
    ]
