# Generated by Django 4.2.7 on 2023-11-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_column='Мероприятие', db_comment='Мероприятие, к которому относится шаблон', help_text='Мероприятие, к которому относится шаблон1', max_length=200)),
            ],
        ),
    ]
